apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "version-checker.fullname" . }}-nginx-config
  labels:
    {{- include "version-checker.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginx.config | indent 4 }}