apiVersion: v1
kind: Service
metadata:
  name: {{ include "version-checker.fullname" . }}
  labels:
    {{- include "version-checker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "version-checker.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.rollouts.enabled (eq .Values.rollouts.strategy "blueGreen") }}
# Preview service for Blue-Green deployments
apiVersion: v1
kind: Service
metadata:
  name: {{ include "version-checker.fullname" . }}-preview
  labels:
    {{- include "version-checker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "version-checker.selectorLabels" . | nindent 4 }}
{{- end }}