services:
  version-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: version-checker-v1
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NGINX_ENV=production
    networks:
      - version-checker-network

networks:
  version-checker-network:
    driver: bridge 